### ISSUE TITLE
Number of cells != number of sites, number of sites != number of input points

### ISSUE THREAD

**Issue by mmarklar** [fesoliveira014/voronator-rs#14]
This might not be a bug. It might be my misunderstanding.

That being said, I expected that the number of sites to be equal to the number of input points. The behavior I see is that sites.len() is input.len() + 4. However, the number of cells == the number of input points. This causes ramifications such as the neighbor indices pointing to cells/inputs that don't exist.

From my tests it seems you can just ignore neighbors with indices > number of cells, but I wanted to raise this in case it is an actual issue.

**Comment by fesoliveira014** [comment]
It has been a while since I touched the code, but from my understanding that is intended to an extent. The extra 4 points are the vertices of the enclosing bounding box for the diagram, and are added to ensure the diagram is clipped to the bounding polygon (a box by default). 

I believe that the behaviour you are expecting is for the resulting diagram to not be clipped. I implement this approach for the Centroid Diagram, and it should not be hard to implement an alternative without the bounding polygon for the Voronoi diagram as well.

**Comment by mmarklar** [comment]
Thanks for the reply, and for the library!

I see what you're talking about with the bounding box. My recommendation would be to just add to the documentation, I think the way it works currently is fine. If there is some way I can contribute that let me know. Thanks again
